apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vikunja-postgres
  labels:
    app: vikunja-postgres
spec:
  selector:
    matchLabels:
      app: vikunja-postgres
  serviceName: "vikunja-postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: vikunja-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: VIKUNJA_DATABASE_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.persistence.size }}