apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  labels:
    app: vikunja
data:
  VIKUNJA_DATABASE_TYPE: {{ .Values.db.type | quote }}
  VIKUNJA_DATABASE_HOST: {{ .Values.db.host | quote }}
  VIKUNJA_DATABASE_USER: {{ .Values.db.user | quote }}
  VIKUNJA_DATABASE_DATABASE: {{ .Values.db.database | quote }}