apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  replicas: {{ .Values.vikunja.replicas }}
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: "{{ .Values.vikunja.image.repository }}:{{ .Values.vikunja.image.tag }}"
          imagePullPolicy: {{ .Values.vikunja.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.vikunja.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: vikunja-config
            - secretRef:
                name: vikunja-secret
          resources:
            requests:
              memory: {{ .Values.vikunja.resources.requests.memory }}
              cpu: {{ .Values.vikunja.resources.requests.cpu }}
            limits:
              memory: {{ .Values.vikunja.resources.limits.memory }}
              cpu: {{ .Values.vikunja.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10