apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vikunja-ingress
  labels:
    app: vikunja
  annotations:
    # Tell cert-manager to manage the certificate
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Traefik-specific entrypoint
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: {{ .Values.vikunja.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vikunja
                port:
                  number: {{ .Values.vikunja.servicePort }}
  tls:
    - hosts:
        - {{ .Values.vikunja.host }}
      secretName: vikunja-tls