apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  labels:
    app: vikunja
type: Opaque
data:
  VIKUNJA_DATABASE_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  VIKUNJA_MAILER_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}