apiVersion: v1
kind: Service
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vikunja.servicePort }}
      targetPort: {{ .Values.vikunja.port }}
      protocol: TCP
      name: http
  selector:
    app: vikunja
