/*
Vikunja API

# Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

API version: v0.24.6
Contact: hello@vikunja.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelsTaskBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsTaskBucket{}

// ModelsTaskBucket struct for ModelsTaskBucket
type ModelsTaskBucket struct {
	BucketId      *int32 `json:"bucket_id,omitempty"`
	ProjectViewId *int32 `json:"project_view_id,omitempty"`
	TaskDone      *bool  `json:"task_done,omitempty"`
	TaskId        *int32 `json:"task_id,omitempty"`
}

// NewModelsTaskBucket instantiates a new ModelsTaskBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsTaskBucket() *ModelsTaskBucket {
	this := ModelsTaskBucket{}
	return &this
}

// NewModelsTaskBucketWithDefaults instantiates a new ModelsTaskBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsTaskBucketWithDefaults() *ModelsTaskBucket {
	this := ModelsTaskBucket{}
	return &this
}

// GetBucketId returns the BucketId field value if set, zero value otherwise.
func (o *ModelsTaskBucket) GetBucketId() int32 {
	if o == nil || IsNil(o.BucketId) {
		var ret int32
		return ret
	}
	return *o.BucketId
}

// GetBucketIdOk returns a tuple with the BucketId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskBucket) GetBucketIdOk() (*int32, bool) {
	if o == nil || IsNil(o.BucketId) {
		return nil, false
	}
	return o.BucketId, true
}

// HasBucketId returns a boolean if a field has been set.
func (o *ModelsTaskBucket) HasBucketId() bool {
	if o != nil && !IsNil(o.BucketId) {
		return true
	}

	return false
}

// SetBucketId gets a reference to the given int32 and assigns it to the BucketId field.
func (o *ModelsTaskBucket) SetBucketId(v int32) {
	o.BucketId = &v
}

// GetProjectViewId returns the ProjectViewId field value if set, zero value otherwise.
func (o *ModelsTaskBucket) GetProjectViewId() int32 {
	if o == nil || IsNil(o.ProjectViewId) {
		var ret int32
		return ret
	}
	return *o.ProjectViewId
}

// GetProjectViewIdOk returns a tuple with the ProjectViewId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskBucket) GetProjectViewIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectViewId) {
		return nil, false
	}
	return o.ProjectViewId, true
}

// HasProjectViewId returns a boolean if a field has been set.
func (o *ModelsTaskBucket) HasProjectViewId() bool {
	if o != nil && !IsNil(o.ProjectViewId) {
		return true
	}

	return false
}

// SetProjectViewId gets a reference to the given int32 and assigns it to the ProjectViewId field.
func (o *ModelsTaskBucket) SetProjectViewId(v int32) {
	o.ProjectViewId = &v
}

// GetTaskDone returns the TaskDone field value if set, zero value otherwise.
func (o *ModelsTaskBucket) GetTaskDone() bool {
	if o == nil || IsNil(o.TaskDone) {
		var ret bool
		return ret
	}
	return *o.TaskDone
}

// GetTaskDoneOk returns a tuple with the TaskDone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskBucket) GetTaskDoneOk() (*bool, bool) {
	if o == nil || IsNil(o.TaskDone) {
		return nil, false
	}
	return o.TaskDone, true
}

// HasTaskDone returns a boolean if a field has been set.
func (o *ModelsTaskBucket) HasTaskDone() bool {
	if o != nil && !IsNil(o.TaskDone) {
		return true
	}

	return false
}

// SetTaskDone gets a reference to the given bool and assigns it to the TaskDone field.
func (o *ModelsTaskBucket) SetTaskDone(v bool) {
	o.TaskDone = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *ModelsTaskBucket) GetTaskId() int32 {
	if o == nil || IsNil(o.TaskId) {
		var ret int32
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskBucket) GetTaskIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *ModelsTaskBucket) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given int32 and assigns it to the TaskId field.
func (o *ModelsTaskBucket) SetTaskId(v int32) {
	o.TaskId = &v
}

func (o ModelsTaskBucket) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsTaskBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BucketId) {
		toSerialize["bucket_id"] = o.BucketId
	}
	if !IsNil(o.ProjectViewId) {
		toSerialize["project_view_id"] = o.ProjectViewId
	}
	if !IsNil(o.TaskDone) {
		toSerialize["task_done"] = o.TaskDone
	}
	if !IsNil(o.TaskId) {
		toSerialize["task_id"] = o.TaskId
	}
	return toSerialize, nil
}

type NullableModelsTaskBucket struct {
	value *ModelsTaskBucket
	isSet bool
}

func (v NullableModelsTaskBucket) Get() *ModelsTaskBucket {
	return v.value
}

func (v *NullableModelsTaskBucket) Set(val *ModelsTaskBucket) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsTaskBucket) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsTaskBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsTaskBucket(val *ModelsTaskBucket) *NullableModelsTaskBucket {
	return &NullableModelsTaskBucket{value: val, isSet: true}
}

func (v NullableModelsTaskBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsTaskBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
