/*
Vikunja API

# Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

API version: v0.24.6
Contact: hello@vikunja.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1LegalInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1LegalInfo{}

// V1LegalInfo struct for V1LegalInfo
type V1LegalInfo struct {
	ImprintUrl *string `json:"imprint_url,omitempty"`
	PrivacyPolicyUrl *string `json:"privacy_policy_url,omitempty"`
}

// NewV1LegalInfo instantiates a new V1LegalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1LegalInfo() *V1LegalInfo {
	this := V1LegalInfo{}
	return &this
}

// NewV1LegalInfoWithDefaults instantiates a new V1LegalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1LegalInfoWithDefaults() *V1LegalInfo {
	this := V1LegalInfo{}
	return &this
}

// GetImprintUrl returns the ImprintUrl field value if set, zero value otherwise.
func (o *V1LegalInfo) GetImprintUrl() string {
	if o == nil || IsNil(o.ImprintUrl) {
		var ret string
		return ret
	}
	return *o.ImprintUrl
}

// GetImprintUrlOk returns a tuple with the ImprintUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LegalInfo) GetImprintUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImprintUrl) {
		return nil, false
	}
	return o.ImprintUrl, true
}

// HasImprintUrl returns a boolean if a field has been set.
func (o *V1LegalInfo) HasImprintUrl() bool {
	if o != nil && !IsNil(o.ImprintUrl) {
		return true
	}

	return false
}

// SetImprintUrl gets a reference to the given string and assigns it to the ImprintUrl field.
func (o *V1LegalInfo) SetImprintUrl(v string) {
	o.ImprintUrl = &v
}

// GetPrivacyPolicyUrl returns the PrivacyPolicyUrl field value if set, zero value otherwise.
func (o *V1LegalInfo) GetPrivacyPolicyUrl() string {
	if o == nil || IsNil(o.PrivacyPolicyUrl) {
		var ret string
		return ret
	}
	return *o.PrivacyPolicyUrl
}

// GetPrivacyPolicyUrlOk returns a tuple with the PrivacyPolicyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LegalInfo) GetPrivacyPolicyUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PrivacyPolicyUrl) {
		return nil, false
	}
	return o.PrivacyPolicyUrl, true
}

// HasPrivacyPolicyUrl returns a boolean if a field has been set.
func (o *V1LegalInfo) HasPrivacyPolicyUrl() bool {
	if o != nil && !IsNil(o.PrivacyPolicyUrl) {
		return true
	}

	return false
}

// SetPrivacyPolicyUrl gets a reference to the given string and assigns it to the PrivacyPolicyUrl field.
func (o *V1LegalInfo) SetPrivacyPolicyUrl(v string) {
	o.PrivacyPolicyUrl = &v
}

func (o V1LegalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1LegalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImprintUrl) {
		toSerialize["imprint_url"] = o.ImprintUrl
	}
	if !IsNil(o.PrivacyPolicyUrl) {
		toSerialize["privacy_policy_url"] = o.PrivacyPolicyUrl
	}
	return toSerialize, nil
}

type NullableV1LegalInfo struct {
	value *V1LegalInfo
	isSet bool
}

func (v NullableV1LegalInfo) Get() *V1LegalInfo {
	return v.value
}

func (v *NullableV1LegalInfo) Set(val *V1LegalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableV1LegalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableV1LegalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1LegalInfo(val *V1LegalInfo) *NullableV1LegalInfo {
	return &NullableV1LegalInfo{value: val, isSet: true}
}

func (v NullableV1LegalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1LegalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


