/*
Vikunja API

# Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

API version: v0.24.6
Contact: hello@vikunja.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelsTaskCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsTaskCollection{}

// ModelsTaskCollection struct for ModelsTaskCollection
type ModelsTaskCollection struct {
	// The filter query to match tasks by. Check out https://vikunja.io/docs/filters for a full explanation.
	Filter *string `json:"filter,omitempty"`
	// If set to true, the result will also include null values
	FilterIncludeNulls *bool `json:"filter_include_nulls,omitempty"`
	// The query parameter to order the items by. This can be either asc or desc, with asc being the default.
	OrderBy []string `json:"order_by,omitempty"`
	// The query parameter to sort by. This is for ex. done, priority, etc.
	SortBy []string `json:"sort_by,omitempty"`
}

// NewModelsTaskCollection instantiates a new ModelsTaskCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsTaskCollection() *ModelsTaskCollection {
	this := ModelsTaskCollection{}
	return &this
}

// NewModelsTaskCollectionWithDefaults instantiates a new ModelsTaskCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsTaskCollectionWithDefaults() *ModelsTaskCollection {
	this := ModelsTaskCollection{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *ModelsTaskCollection) GetFilter() string {
	if o == nil || IsNil(o.Filter) {
		var ret string
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskCollection) GetFilterOk() (*string, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ModelsTaskCollection) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given string and assigns it to the Filter field.
func (o *ModelsTaskCollection) SetFilter(v string) {
	o.Filter = &v
}

// GetFilterIncludeNulls returns the FilterIncludeNulls field value if set, zero value otherwise.
func (o *ModelsTaskCollection) GetFilterIncludeNulls() bool {
	if o == nil || IsNil(o.FilterIncludeNulls) {
		var ret bool
		return ret
	}
	return *o.FilterIncludeNulls
}

// GetFilterIncludeNullsOk returns a tuple with the FilterIncludeNulls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskCollection) GetFilterIncludeNullsOk() (*bool, bool) {
	if o == nil || IsNil(o.FilterIncludeNulls) {
		return nil, false
	}
	return o.FilterIncludeNulls, true
}

// HasFilterIncludeNulls returns a boolean if a field has been set.
func (o *ModelsTaskCollection) HasFilterIncludeNulls() bool {
	if o != nil && !IsNil(o.FilterIncludeNulls) {
		return true
	}

	return false
}

// SetFilterIncludeNulls gets a reference to the given bool and assigns it to the FilterIncludeNulls field.
func (o *ModelsTaskCollection) SetFilterIncludeNulls(v bool) {
	o.FilterIncludeNulls = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *ModelsTaskCollection) GetOrderBy() []string {
	if o == nil || IsNil(o.OrderBy) {
		var ret []string
		return ret
	}
	return o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskCollection) GetOrderByOk() ([]string, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *ModelsTaskCollection) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given []string and assigns it to the OrderBy field.
func (o *ModelsTaskCollection) SetOrderBy(v []string) {
	o.OrderBy = v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *ModelsTaskCollection) GetSortBy() []string {
	if o == nil || IsNil(o.SortBy) {
		var ret []string
		return ret
	}
	return o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTaskCollection) GetSortByOk() ([]string, bool) {
	if o == nil || IsNil(o.SortBy) {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *ModelsTaskCollection) HasSortBy() bool {
	if o != nil && !IsNil(o.SortBy) {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given []string and assigns it to the SortBy field.
func (o *ModelsTaskCollection) SetSortBy(v []string) {
	o.SortBy = v
}

func (o ModelsTaskCollection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsTaskCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.FilterIncludeNulls) {
		toSerialize["filter_include_nulls"] = o.FilterIncludeNulls
	}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.SortBy) {
		toSerialize["sort_by"] = o.SortBy
	}
	return toSerialize, nil
}

type NullableModelsTaskCollection struct {
	value *ModelsTaskCollection
	isSet bool
}

func (v NullableModelsTaskCollection) Get() *ModelsTaskCollection {
	return v.value
}

func (v *NullableModelsTaskCollection) Set(val *ModelsTaskCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsTaskCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsTaskCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsTaskCollection(val *ModelsTaskCollection) *NullableModelsTaskCollection {
	return &NullableModelsTaskCollection{value: val, isSet: true}
}

func (v NullableModelsTaskCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsTaskCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
