/*
Vikunja API

# Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

API version: v0.24.6
Contact: hello@vikunja.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1UserAvatarProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UserAvatarProvider{}

// V1UserAvatarProvider struct for V1UserAvatarProvider
type V1UserAvatarProvider struct {
	// The avatar provider. Valid types are `gravatar` (uses the user email), `upload`, `initials`, `marble` (generates a random avatar for each user), `default`.
	AvatarProvider *string `json:"avatar_provider,omitempty"`
}

// NewV1UserAvatarProvider instantiates a new V1UserAvatarProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UserAvatarProvider() *V1UserAvatarProvider {
	this := V1UserAvatarProvider{}
	return &this
}

// NewV1UserAvatarProviderWithDefaults instantiates a new V1UserAvatarProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UserAvatarProviderWithDefaults() *V1UserAvatarProvider {
	this := V1UserAvatarProvider{}
	return &this
}

// GetAvatarProvider returns the AvatarProvider field value if set, zero value otherwise.
func (o *V1UserAvatarProvider) GetAvatarProvider() string {
	if o == nil || IsNil(o.AvatarProvider) {
		var ret string
		return ret
	}
	return *o.AvatarProvider
}

// GetAvatarProviderOk returns a tuple with the AvatarProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserAvatarProvider) GetAvatarProviderOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarProvider) {
		return nil, false
	}
	return o.AvatarProvider, true
}

// HasAvatarProvider returns a boolean if a field has been set.
func (o *V1UserAvatarProvider) HasAvatarProvider() bool {
	if o != nil && !IsNil(o.AvatarProvider) {
		return true
	}

	return false
}

// SetAvatarProvider gets a reference to the given string and assigns it to the AvatarProvider field.
func (o *V1UserAvatarProvider) SetAvatarProvider(v string) {
	o.AvatarProvider = &v
}

func (o V1UserAvatarProvider) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UserAvatarProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarProvider) {
		toSerialize["avatar_provider"] = o.AvatarProvider
	}
	return toSerialize, nil
}

type NullableV1UserAvatarProvider struct {
	value *V1UserAvatarProvider
	isSet bool
}

func (v NullableV1UserAvatarProvider) Get() *V1UserAvatarProvider {
	return v.value
}

func (v *NullableV1UserAvatarProvider) Set(val *V1UserAvatarProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UserAvatarProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UserAvatarProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UserAvatarProvider(val *V1UserAvatarProvider) *NullableV1UserAvatarProvider {
	return &NullableV1UserAvatarProvider{value: val, isSet: true}
}

func (v NullableV1UserAvatarProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UserAvatarProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


