/*
Vikunja API

# Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

API version: v0.24.6
Contact: hello@vikunja.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelsSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsSubscription{}

// ModelsSubscription struct for ModelsSubscription
type ModelsSubscription struct {
	// A timestamp when this subscription was created. You cannot change this value.
	Created *string `json:"created,omitempty"`
	Entity  *int32  `json:"entity,omitempty"`
	// The id of the entity to subscribe to.
	EntityId *int32 `json:"entity_id,omitempty"`
	// The numeric ID of the subscription
	Id *int32 `json:"id,omitempty"`
}

// NewModelsSubscription instantiates a new ModelsSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsSubscription() *ModelsSubscription {
	this := ModelsSubscription{}
	return &this
}

// NewModelsSubscriptionWithDefaults instantiates a new ModelsSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsSubscriptionWithDefaults() *ModelsSubscription {
	this := ModelsSubscription{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ModelsSubscription) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSubscription) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ModelsSubscription) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *ModelsSubscription) SetCreated(v string) {
	o.Created = &v
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *ModelsSubscription) GetEntity() int32 {
	if o == nil || IsNil(o.Entity) {
		var ret int32
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSubscription) GetEntityOk() (*int32, bool) {
	if o == nil || IsNil(o.Entity) {
		return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *ModelsSubscription) HasEntity() bool {
	if o != nil && !IsNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given int32 and assigns it to the Entity field.
func (o *ModelsSubscription) SetEntity(v int32) {
	o.Entity = &v
}

// GetEntityId returns the EntityId field value if set, zero value otherwise.
func (o *ModelsSubscription) GetEntityId() int32 {
	if o == nil || IsNil(o.EntityId) {
		var ret int32
		return ret
	}
	return *o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSubscription) GetEntityIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityId) {
		return nil, false
	}
	return o.EntityId, true
}

// HasEntityId returns a boolean if a field has been set.
func (o *ModelsSubscription) HasEntityId() bool {
	if o != nil && !IsNil(o.EntityId) {
		return true
	}

	return false
}

// SetEntityId gets a reference to the given int32 and assigns it to the EntityId field.
func (o *ModelsSubscription) SetEntityId(v int32) {
	o.EntityId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsSubscription) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsSubscription) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsSubscription) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ModelsSubscription) SetId(v int32) {
	o.Id = &v
}

func (o ModelsSubscription) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	if !IsNil(o.EntityId) {
		toSerialize["entity_id"] = o.EntityId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableModelsSubscription struct {
	value *ModelsSubscription
	isSet bool
}

func (v NullableModelsSubscription) Get() *ModelsSubscription {
	return v.value
}

func (v *NullableModelsSubscription) Set(val *ModelsSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsSubscription(val *ModelsSubscription) *NullableModelsSubscription {
	return &NullableModelsSubscription{value: val, isSet: true}
}

func (v NullableModelsSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
