/*
Vikunja API

# Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

API version: v0.24.6
Contact: hello@vikunja.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1UserWithSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UserWithSettings{}

// V1UserWithSettings struct for V1UserWithSettings
type V1UserWithSettings struct {
	// A timestamp when this task was created. You cannot change this value.
	Created *string `json:"created,omitempty"`
	DeletionScheduledAt *string `json:"deletion_scheduled_at,omitempty"`
	// The user's email address.
	Email *string `json:"email,omitempty"`
	// The unique, numeric id of this user.
	Id *int32 `json:"id,omitempty"`
	IsLocalUser *bool `json:"is_local_user,omitempty"`
	// The full name of the user.
	Name *string `json:"name,omitempty"`
	Settings *V1UserSettings `json:"settings,omitempty"`
	// A timestamp when this task was last updated. You cannot change this value.
	Updated *string `json:"updated,omitempty"`
	// The username of the user. Is always unique.
	Username *string `json:"username,omitempty"`
}

// NewV1UserWithSettings instantiates a new V1UserWithSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UserWithSettings() *V1UserWithSettings {
	this := V1UserWithSettings{}
	return &this
}

// NewV1UserWithSettingsWithDefaults instantiates a new V1UserWithSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UserWithSettingsWithDefaults() *V1UserWithSettings {
	this := V1UserWithSettings{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *V1UserWithSettings) SetCreated(v string) {
	o.Created = &v
}

// GetDeletionScheduledAt returns the DeletionScheduledAt field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetDeletionScheduledAt() string {
	if o == nil || IsNil(o.DeletionScheduledAt) {
		var ret string
		return ret
	}
	return *o.DeletionScheduledAt
}

// GetDeletionScheduledAtOk returns a tuple with the DeletionScheduledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetDeletionScheduledAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeletionScheduledAt) {
		return nil, false
	}
	return o.DeletionScheduledAt, true
}

// HasDeletionScheduledAt returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasDeletionScheduledAt() bool {
	if o != nil && !IsNil(o.DeletionScheduledAt) {
		return true
	}

	return false
}

// SetDeletionScheduledAt gets a reference to the given string and assigns it to the DeletionScheduledAt field.
func (o *V1UserWithSettings) SetDeletionScheduledAt(v string) {
	o.DeletionScheduledAt = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *V1UserWithSettings) SetEmail(v string) {
	o.Email = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *V1UserWithSettings) SetId(v int32) {
	o.Id = &v
}

// GetIsLocalUser returns the IsLocalUser field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetIsLocalUser() bool {
	if o == nil || IsNil(o.IsLocalUser) {
		var ret bool
		return ret
	}
	return *o.IsLocalUser
}

// GetIsLocalUserOk returns a tuple with the IsLocalUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetIsLocalUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLocalUser) {
		return nil, false
	}
	return o.IsLocalUser, true
}

// HasIsLocalUser returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasIsLocalUser() bool {
	if o != nil && !IsNil(o.IsLocalUser) {
		return true
	}

	return false
}

// SetIsLocalUser gets a reference to the given bool and assigns it to the IsLocalUser field.
func (o *V1UserWithSettings) SetIsLocalUser(v bool) {
	o.IsLocalUser = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1UserWithSettings) SetName(v string) {
	o.Name = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetSettings() V1UserSettings {
	if o == nil || IsNil(o.Settings) {
		var ret V1UserSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetSettingsOk() (*V1UserSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given V1UserSettings and assigns it to the Settings field.
func (o *V1UserWithSettings) SetSettings(v V1UserSettings) {
	o.Settings = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetUpdated() string {
	if o == nil || IsNil(o.Updated) {
		var ret string
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given string and assigns it to the Updated field.
func (o *V1UserWithSettings) SetUpdated(v string) {
	o.Updated = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *V1UserWithSettings) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UserWithSettings) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *V1UserWithSettings) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *V1UserWithSettings) SetUsername(v string) {
	o.Username = &v
}

func (o V1UserWithSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UserWithSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.DeletionScheduledAt) {
		toSerialize["deletion_scheduled_at"] = o.DeletionScheduledAt
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IsLocalUser) {
		toSerialize["is_local_user"] = o.IsLocalUser
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableV1UserWithSettings struct {
	value *V1UserWithSettings
	isSet bool
}

func (v NullableV1UserWithSettings) Get() *V1UserWithSettings {
	return v.value
}

func (v *NullableV1UserWithSettings) Set(val *V1UserWithSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UserWithSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UserWithSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UserWithSettings(val *V1UserWithSettings) *NullableV1UserWithSettings {
	return &NullableV1UserWithSettings{value: val, isSet: true}
}

func (v NullableV1UserWithSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UserWithSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


