# .github/workflows/build-lint-test.yml
name: Build, lint, and test Vikunja-mcp

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: ./go.sum

    - name: Install golangci-lint v2
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh \
          | sh -s -- -b $(go env GOPATH)/bin v2.1.6

    - name: Lint
      run: golangci-lint run ./...

    - name: Run unit tests
      run: go test -v -coverprofile=coverage.out ./...
